title: "Matt Whipple"
email: "matt@mattwhipple.com"
description: "Web Site for Software Engineer Matt Whipple"
baseurl: "" #Relative root prefix
url: "http://www.mattwhipple.com"
excerpt_separator: <!--more-->
paginate: 5

kramdown:
  input: GFM

gems:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
