title: "Matt Whipple"
email: "matt@mattwhipple.com"
description: "Web Site for Software Engineer Matt Whipple"
baseurl: "" #Relative root prefix
url: "http://www.mattwhipple.com"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"